<?php
/**
 * test_email_view.php
 *
 * Renders the responsive email templates generated by mailer.php
 * for direct visual inspection in the browser.
 */

require_once 'mailer.php';

// Define temporary mock values
$recipientName = "Clarissa Ferraren";
$code = "482059";
$password = "GCST-Temp-9284!";
$student_number = "STUD-2026-0042";

// 1. Password Reset Template
$reset_title = "Password Reset Code";
$reset_greeting = "Hello " . htmlspecialchars($recipientName, ENT_QUOTES, 'UTF-8') . ",";
$reset_content = "
    <p style='margin: 0 0 16px 0;'>We received a request to reset the password associated with your account on the Faculty Evaluation System.</p>
    <p style='margin: 0 0 16px 0;'>Please use the 6-digit verification code below to complete your password reset request.</p>
    <p style='margin: 0 0 16px 0;'>If you did not make this request, you can safely ignore this email; your password will remain unchanged.</p>
";
$reset_highlight = [
    'label' => 'Verification Code',
    'value' => $code,
    'subtext' => 'This code expires in 10 minutes'
];
$reset_cta = [
    'label' => 'Go to Login Page',
    'url' => 'http://localhost/FacultyEvaluation/EvalMain.php'
];
$reset_html = getEmailHTML($reset_title, $reset_greeting, $reset_content, $reset_highlight, $reset_cta);


// 2. Welcome / Temporary Password Template
$welcome_title = "Welcome to Faculty Evaluation System";
$welcome_greeting = "Hello " . htmlspecialchars($recipientName, ENT_QUOTES, 'UTF-8') . ",";
$welcome_content = "
    <p style='margin: 0 0 16px 0;'>Your student account has been successfully created. You can now access the Faculty Evaluation System using your credentials below.</p>
    <p style='margin: 0 0 16px 0;'><strong>Student Number:</strong> " . htmlspecialchars($student_number, ENT_QUOTES, 'UTF-8') . "</p>
    <p style='margin: 0 0 16px 0;'>For security reasons, we strongly recommend that you change your password immediately after logging in for the first time.</p>
";
$welcome_highlight = [
    'label' => 'Temporary Password',
    'value' => $password,
    'subtext' => 'Keep this password secure'
];
$welcome_cta = [
    'label' => 'Log In to System',
    'url' => 'http://localhost/FacultyEvaluation/EvalMain.php'
];
$welcome_html = getEmailHTML($welcome_title, $welcome_greeting, $welcome_content, $welcome_highlight, $welcome_cta);

// Handle selection toggle via query param
$view = $_GET['view'] ?? 'reset';

?>
<!DOCTYPE html>
<html>
<head>
    <title>Email Template Visual Preview</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background: #0f172a;
            color: #f8fafc;
            margin: 0;
            padding: 0;
        }
        .preview-bar {
            background: #1e293b;
            padding: 15px 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid #334155;
            box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);
        }
        .preview-title {
            font-size: 16px;
            font-weight: 700;
            margin: 0;
        }
        .preview-btn {
            background: #3b82f6;
            color: #ffffff;
            border: none;
            padding: 8px 16px;
            border-radius: 6px;
            text-decoration: none;
            font-size: 14px;
            font-weight: 600;
            margin-left: 10px;
            transition: background 0.2s;
        }
        .preview-btn:hover {
            background: #2563eb;
        }
        .preview-btn.active {
            background: #059669;
        }
        .email-iframe-container {
            display: flex;
            justify-content: center;
            padding: 20px;
            height: calc(100vh - 80px);
            box-sizing: border-box;
        }
        iframe {
            width: 100%;
            max-width: 700px;
            height: 100%;
            background: #f1f5f9;
            border: 1px solid #334155;
            border-radius: 12px;
            box-shadow: 0 10px 15px -3px rgba(0,0,0,0.3);
        }
    </style>
</head>
<body>

<div class="preview-bar">
    <h2 class="preview-title">Visual Email Template Previewer</h2>
    <div>
        <a href="?view=reset" class="preview-btn <?= $view === 'reset' ? 'active' : '' ?>">Password Reset Code</a>
        <a href="?view=welcome" class="preview-btn <?= $view === 'welcome' ? 'active' : '' ?>">Welcome & Temp Password</a>
    </div>
</div>

<div class="email-iframe-container">
    <?php if ($view === 'reset'): ?>
        <iframe srcdoc="<?= htmlspecialchars($reset_html, ENT_QUOTES, 'UTF-8') ?>"></iframe>
    <?php else: ?>
        <iframe srcdoc="<?= htmlspecialchars($welcome_html, ENT_QUOTES, 'UTF-8') ?>"></iframe>
    <?php endif; ?>
</div>

</body>
</html>
